---
- name: Install ufw
  ansible.builtin.apt:
    name: ufw
    state: present

- name: Create rules
  community.general.ufw:
    direction: "{{ item.direction | default(omit) }}"
    from_ip: "{{ item.from_ip | default(omit) }}"
    from_port: "{{ item.from_port | default(omit) }}"
    interface: "{{ item.interface | default(omit) }}"
    proto: "{{ item.proto | default(omit) }}"
    rule: "{{ item.rule | default('allow') }}"
    to_ip: "{{ item.to_ip | default(omit) }}"
    to_port: "{{ item.to_port | default(omit) }}"
  with_items: "{{ ufw_rules_to_create }}"

- name: Delete rules
  community.general.ufw:
    direction: "{{ item.direction | default(omit) }}"
    from_ip: "{{ item.from_ip | default(omit) }}"
    from_port: "{{ item.from_port | default(omit) }}"
    interface: "{{ item.interface | default(omit) }}"
    proto: "{{ item.proto | default(omit) }}"
    rule: "{{ item.rule | default('allow') }}"
    to_ip: "{{ item.to_ip | default(omit) }}"
    to_port: "{{ item.to_port | default(omit) }}"
    delete: true
  with_items: "{{ ufw_rules_to_delete }}"

- name: Set default policy
  community.general.ufw:
    policy: "{{ item.policy }}"
    direction: "{{ item.direction }}"
  with_items: "{{ ufw_default_policy }}"

- name: Enable and start ufw
  community.general.ufw:
    state: enabled
